<img src="https://i.imgur.com/nhTNC7J.png"> 

<p>

**Autor:**
  <a href="https://github.com/JosManoel">Manoel Freitas</a>
</p>

Durante o desenvolvimento de aplica√ß√µes n√£o ser√£o raras √†s vezes em que ser√° necess√°rio tratar algum evento indesejado que ocorreu durante a execu√ß√£o do software, seja por bugs no desenvolvimento ou entradas incorretas do usu√°rio.

Para estes casos, na programa√ß√£o, essas ocorr√™ncias s√£o solucionadas pelos mecanismos de tratamento de exce√ß√µes, respons√°veis por direcionar o programa para uma **rotina de tratamento**, quando o fluxo normal √© interrompido. 

***
<h2 id="sumario">üßÆ Sum√°rio</h2>
  
  * <a href="#O_que_e_uma_excecao">O que √© uma exce√ß√£o?</a>
      * <a href="#Checked">Exce√ß√µes checadas (Checked Exceptions)</a>
      * <a href="#Unchecked">Exce√ß√µes n√£o checadas (Unchecked Exceptions)</a>
  * <a href="#Tratando_excecoes">Tratando exce√ß√µes</a>
      * <a href="#Catch">Try... Catch</a>
      * <a href="#On">On</a>
      * <a href="#Finally">Finally</a>
  * <a href="#Throw">Throw</a>
  * <a href="#Rethrow">Rethrow</a>
  * <a href="#Personalizadas">Exce√ß√µes personalizadas</a>
  * <a href="#Dart_core-exception">Dart Core: Exceptions</a>
  * <a href="#Dart_core-error">Dart Core: Error</a>
  * <a href="#leitura_e_link">üìö Leitura e links recomendado</a>
  * <a href="#licenca">üßæLicen√ßa</a>

***


<h2 id="O_que_e_uma_excecao">O que √© uma exce√ß√£o?</h2>

No desenvolvimento de software, uma **exce√ß√£o** ocorre quando um evento indesejado interrompe o fluxo de execu√ß√£o convencional do c√≥digo, seja por algum erro de programa√ß√£o ou alguma entrada inv√°lida do usu√°rio. Isso pode acontecer ao informar um valor num√©rico, quando era esperando uma string, ou quando estava esperando algum valor retornado como nulo.


<h3 align="center">Fluxo de execu√ß√£o de um software</h3>

<p align="center">
    <img src="https://i.imgur.com/QjQMGVp.png" height="320"> 
</p>

> Neste exemplo podemos observar a execu√ß√£o de um programa que recebeu uma exce√ß√£o na 2¬∞ instru√ß√£o, levando a um tratamento e a sua finaliza√ß√£o. Este fluxograma representa uma quebra clara no fluxo de execu√ß√£o de um software, que acontece sempre que uma exce√ß√£o ocorre.

As exce√ß√µes ainda podem ser classificadas em dois tipos: as **exce√ß√µes checadas (checked)** e as **exce√ß√µes n√£o checadas (unchecked)**. 

<h3 id="Checked">Exce√ß√µes checadas (Checked Exceptions)</h3>

As exce√ß√µes chegadas, de maneira geral, s√£o utilizadas para sinalizar condi√ß√µes inv√°lidas em √°reas que necessitam obrigatoriamente de uma resolu√ß√£o imediata. Um bom exemplo disso pode ser visto em softwares de leitura em pdf, que retornar√° uma mensagem de erro com a sinaliza√ß√£o de "**Arquivo inv√°lido**", quando um formato de documento diferente do pdf for submetido. 

Essa √© uma das principais caracter√≠sticas de uma **checked exception**: a exce√ß√£o deve obrigatoriamente ser tratada, seja com um bloco **try-catch** ou outros m√©todos que a linguagem utilizada disponibilizar. 

<h3 id="Unchecked">Exce√ß√µes n√£o checadas (Unchecked Exceptions)</h3>

As exce√ß√µes n√£o checadas funcionam de maneira contr√°ria as exce√ß√µes checadas, j√° que n√£o existe a necessidade de trat√°-las, apesar do erro ou bug continuar em execu√ß√£o at√© que sejam verificadas por algum m√©todo desenvolvido pelo programador, ou at√© que o programa seja encerrado inesperadamente.

> Este √© o tipo mais comum, presente na maioria das linguagens de programa√ß√£o, incluindo o Dart.

Apesar de exist√™ncia dessas essas duas defini√ß√µes, nem todas as linguagens de programa√ß√£o compartilham das duas exce√ß√µes, como o Ruby, C# e Dart, que n√£o possuem as **checked exceptions**, ao contr√°rio do Java, que utiliza ambas.

Para lidar esses erros, diversas linguagens de programa√ß√£o desenvolveram seus pr√≥prios m√©todos de tratamento, incluindo estruturas condicionais e bibliotecas espec√≠ficas, como a classe exceptions, da biblioteca dart:core, que ser√° abordada a seguir.

<p align="right">
    <a href="#sumario">
        <img src="https://raw.githubusercontent.com/JosManoel/Dart-Study/main/images/icons/voltar_ao_topo.png" height="32">
    </a>
</p>

***

<h2 id="Tratando_excecoes">Tratando exce√ß√µes</h2>

O Dart possui diversas maneiras de lidar com exce√ß√µes, incluindo n√£o lidar com elas. Diferentemente de outras linguagens como o Java, todas as exce√ß√µes do Dart s√£o exce√ß√µes do tipo **unchecked**, o que significa que n√£o √© necess√°rio trat√°-las.

> Quando um exce√ß√£o n√£o √© tratada no Dart a chamada que gerou a exce√ß√£o ser√° suspensa e posteriormente encerrada em conjunto com o programa, caso seja necess√°rio. 

> O Dart ainda possui duas classes de exce√ß√µes, sendo elas a **Exception** e a **Error**, que fazem parte da biblioteca dart:core e ser√£o abordadas posteriormente. 

No Dart as exce√ß√µes basicamente podem ser tratadas utilizando os m√©todos **Try... Catch**, **Finally** e **Throw**.


<h2 id="Catch">Try... Catch</h2>

O conjunto de blocos **Try... Catch** √© bastante utilizado por diversas linguagens de programa√ß√£o, como o Java e JavaScript. No Dart, seu funcionamento ocorre de maneira semelhante as outras ferramentas de desenvolvimento, seguindo a seguinte sintaxe:

*  **Try:** Bloco respons√°vel por "conter" o trecho de c√≥digo que ser√° analisado. Sua fun√ß√£o √© verificar se o c√≥digo que est√° dentro do seu bloco, quando executado, retorna algum erro, _desviando o fluxo de execu√ß√£o_ do programa para um segundo bloco de tratamento, seja ele um **Catch** ou um **On**.

* **Catch** Bloco respons√°vel por executar o tratamento do erro relatado pelo bloco **Try**. Sua fun√ß√£o √© executar uma s√©rie de comportamentos definidos pelo desenvolvedor para o c√≥digo de erro especificado.

<h3 align="center">Sintaxe de utiliza√ß√£o do Try... Catch</h3>

~~~dart

try{
    //Bloco que receber√° o c√≥digo que ser√° analisado pelo try.
}

catch(parametro_de_erro){
    //Bloco respons√°vel por executar o tratamento definido pelo desenvolvedor.
}
~~~

<h3 align="center">Try... Catch - Exemplo pr√°tico</h3>

~~~dart
main() { 
   int saitama_forca = 10; 
   int saitama_cabelo = 0; 
   int saitama_poder;  
   
   try {  
     saitama_poder = saitama_forca ~/ saitama_cabelo;
     print("N√≠vel de poder do Saitama: ${saitama_poder}");
   }  
   catch(e) { 
      print(e); 
   } 
} 
~~~

<p align="center">
    <a href="https://dartpad.dev/?id=2617993072e628d81cd3e0cbe6d41f6a">
        <img src="https://i.imgur.com/Z8T7RJU.png" height="24">
    </a>
</p>

> Experimente aumentar o valor da vari√°vel "saitama_cabelo".

Note que, ao executar este c√≥digo, uma mensagem de erro ser√° exibida ao inv√©s do resultado esperado na vari√°vel "saitama_poder". Isso acontece devido ao erro retornado pela divis√£o por zero, desviando o fluxo comum de execu√ß√£o do c√≥digo para o bloco **Catch**.

Perceba que o erro exibido pelo bloco **Catch** √© proveniente do par√¢metro **_e_**, um par√¢metro de erro retornado pelo bloco **Try** e que pode possuir qualquer nome, apesar de ser convencionalmente atribu√≠do apenas como "e" para erros gen√©ricos.

O erro retornado simboliza uma exce√ß√£o por _"Unsupported operation"_, um erro do tipo _"Error class"_, uma classe de exce√ß√µes suportada pelo Dart e que ser√° abordada posteriormente. 

<p align="right">
    <a href="#sumario">
        <img src="https://raw.githubusercontent.com/JosManoel/Dart-Study/main/images/icons/voltar_ao_topo.png" height="32">
    </a>
</p>

<h2 id="On">On</h2>

O bloco **On** possui um funcionamento semelhante ao bloco **Catch**, por√©m √© destinado ao uso em situa√ß√µes em que j√° se sabe qual ser√° a categoria de erro retornado. Atrav√©s dele √© poss√≠vel realizar o tratamento de exce√ß√µes espec√≠ficas, definidas pelas bibliotecas do dart, seja ela do tipo **Exception** ou **Error**, que ser√£o abordadas posteriormente.

Podemos tomar como exemplo o c√≥digo anterior, j√° que j√° sabemos que o erro retornado √© um erro do tipo _"Unsupported operation"_, da [UnsupportedError class](https://api.dart.dev/stable/2.16.2/dart-core/UnsupportedError-class.html). Portanto, podemos reescrever o c√≥digo como:

<h3 align="center">Try... On - Exemplo pr√°tico</h3>

~~~dart
main() { 
   int saitama_forca = 10; 
   int saitama_cabelo = 0; 
   int saitama_poder;  
   
   try {  
     saitama_poder = saitama_forca ~/ saitama_cabelo;
     print("N√≠vel de poder do Saitama: ${saitama_poder}");
   }  
   on UnsupportedError { 
      print("UnsupportedError: opera√ß√£o inv√°lida"); 
   } 
} 
~~~

<p align="center">
    <a href="https://dartpad.dev/?id=ad550a6fe89ceddce2e1d2cf4d054fc2">
        <img src="https://i.imgur.com/X8nLz0A.png" height="24">
    </a>
</p>

> Os tipos de erros suportados pelo bloco de tratamento On ser√° abordado posteriormente, nos t√≥picos sobre Dart Core Exceptions e Errors.

Note que neste caso n√£o possu√≠mos o par√¢metro de erro, j√° que o bloco **On** n√£o possui suporte a par√¢metros.

O bloco **On** ainda pode ser combinado com o **Catch**, normalmente utilizado quando queremos capturar tanto erros conhecidos como erros desconhecidos. Encadear blocos **On** e **Catch** pode ser bastante √∫til para criar tratamentos de exce√ß√µes robustos em aplica√ß√µes.

<h3 align="center">Sintaxe de utiliza√ß√£o do Try... On/Catch</h3>

~~~dart

try{
    //Bloco que receber√° o c√≥digo que ser√° analisado pelo try.
}

on Excecao_conhecida{
    //Bloco respons√°vel por executar o tratamento definido pelo desenvolvedor
    //para situa√ß√µes pr√©viamente conhecidas.

}
catch(parametro_de_erro){
    //Bloco respons√°vel por executar o tratamento definido pelo desenvolvedor.
}
~~~

<h3 align="center">Try... On/Catch - Exemplo pr√°tico</h3>

~~~dart
main() { 
   main() { 
  // Alterne a vari√°vel "saitama_cabelo" entre "0" e "null"
   var saitama_forca = 10; 
   var saitama_cabelo = 0; 
   var saitama_poder;  
   
   try {  
     saitama_poder = saitama_forca ~/ saitama_cabelo;
     print("N√≠vel de poder do Saitama: ${saitama_poder}");
   }  
   on UnsupportedError{ 
      print("Erro capturado pelo bloco On"); 
      print("UnsupportedError: opera√ß√£o inv√°lida"); 
   }
   catch(e) { 
      print("Erro capturado pelo bloco Catch"); 
      print(e); 
   } 
}   
~~~

<p align="center">
    <a href="https://dartpad.dev/?id=6c5a7d24c33404556d63031e22476b15">
        <img src="https://i.imgur.com/RSX2Sun.png" height="24">
    </a>
</p>


<p align="right">
    <a href="#sumario">
        <img src="https://raw.githubusercontent.com/JosManoel/Dart-Study/main/images/icons/voltar_ao_topo.png" height="32">
    </a>
</p>

<h2 id="Finally">Finally</h2>

O bloco **Finally** funciona como um complemento ao tratamento de exce√ß√µes. Sua fun√ß√£o √© excecutar uma s√©rie de fun√ß√µes definidas pelo desenvolvedor independente do erro reportado pelo bloco **Try**, mesmo que ele n√£o retorne nenhuma exce√ß√£o. Qualquer c√≥digo escrito dentro deste bloco ser√° executado, independente do retorno ou n√£o de algum erro.

O **Finally** pode ser bastante √∫til em situa√ß√µes onde desejamos definir um comportamento padr√£o para a finaliza√ß√£o de um programa. Por exemplo, podemos ter uma situa√ß√£o onde criamos um sistema de login, que sempre pergunta ao usu√°rio se ele deseja realmente sair da p√°gina, independente do login ter retornado algum erro ou n√£o.

<h3 align="center">Sintaxe de utiliza√ß√£o do Try... On/Catch - Finally</h3>

~~~dart

try{
    //Bloco que receber√° o c√≥digo que ser√° analisado pelo try.
}

on Excecao_conhecida{
    //Bloco respons√°vel por executar o tratamento definido pelo desenvolvedor
    //para situa√ß√µes pr√©viamente conhecidas.

}
catch(parametro_de_erro){
    //Bloco respons√°vel por executar o tratamento definido pelo desenvolvedor.
}
finally {
    //Instru√ß√µes que ser√£o executadas independente do erro retornado.
}
~~~

<h3 align="center">Try... On/Catch - Exemplo pr√°tico</h3>

~~~dart
main() { 
   var saitama_forca = 10; 
   var saitama_cabelo = 0; 
   var saitama_poder;  
   
   try {  
     saitama_poder = saitama_forca ~/ saitama_cabelo;
     print("N√≠vel de poder do Saitama: ${saitama_poder}");
   }  
   on UnsupportedError{ 
      print("Erro capturado pelo bloco On"); 
      print("UnsupportedError: opera√ß√£o inv√°lida"); 
   }
   catch(e) { 
      print("Erro capturado pelo bloco Catch"); 
      print(e); 
   }
   finally {
     print("C√°lculo de poder do Saitama encerrado");
   }
}   
~~~

<p align="center">
    <a href="https://dartpad.dev/?id=cb76459c8417f12c2732d249ae009bc2">
        <img src="https://i.imgur.com/xROnijT.png" height="24">
    </a>
</p>

<p align="right">
    <a href="#sumario">
        <img src="https://raw.githubusercontent.com/JosManoel/Dart-Study/main/images/icons/voltar_ao_topo.png" height="32">
    </a>
</p>

***
<h2 id="Throw">Throw</h2>

O m√©todo throw possui uma funcionalidade bastante peculiar: gerar explicitamente uma exce√ß√£o. Atrav√©s do **Throw** √© poss√≠vel criar chamadas para exce√ß√µes que ser√£o tratadas posteriormente, mesmo que n√£o exista propriamente um erro no c√≥digo analisado. Seu funcionamento √© simples, bastando chamar o **Throw** com alguma das classes de exce√ß√µes desejadas. O Throw ainda pode ser combinado a outros elementos, como as fun√ß√µes, para criar as **Exce√ß√µes personalizadas**, que ser√£o abordadas a seguir.

<h3 align="center">Sintaxe de utiliza√ß√£o do Throw</h3>

~~~dart
throw Classe_de_Excecao(parametros_quando_necessario);
~~~

> Alguns tutoriais podem trazer a sintaxe do throw em conjunto com o "new" (throw new), no entanto, segundo a documenta√ß√£o atual do dart, o uso do "new" para criar novas inst√¢ncias n√£o √© mais necess√°rio.

O **Throw** pode ser utilizado para diversos tipos de exce√ß√µes, como o **FormatException** e o **UnsupportedError**, bem como todos os seus par√¢metros definidos pela documenta√ß√£o. Para v√™ lista completa acesse [este link](https://api.dart.dev/stable/2.17.0/dart-core/dart-core-library.html#exceptions).

<h3 align="center">Throw - Exemplo pr√°tico</h3>

~~~dart
main() { 
   var saitama_forca = 10; 
   var saitama_cabelo = 0; 
   var saitama_poder;  
   
   try {  
     if(saitama_cabelo > 0){
        throw FormatException("Saitama deve ser careca");  
     }
     
     saitama_poder = saitama_forca ~/ saitama_cabelo;
     print("N√≠vel de poder do Saitama: ${saitama_poder}");
   }  
   on UnsupportedError{ 
      print("Erro capturado pelo bloco On"); 
      print("UnsupportedError: opera√ß√£o inv√°lida"); 
   }
   catch(e) { 
      print("Erro capturado pelo bloco Catch"); 
      print(e); 
   }
   finally {
     print("C√°lculo de poder do Saitama encerrado");
   }
}   
~~~

> Experimente aumentar o valor da vari√°vel "saitama_cabelo". 

<p align="center">
    <a href="https://dartpad.dev/?id=d5417800ca5c115e617a4875a33117ad">
        <img src="https://i.imgur.com/sbTnZQn.png" height="24">
    </a>
</p>

Note que quando a vari√°vel _"saitama_cabelo"_ possui um valor maior que zero, √© lan√ßado um FormatException com a mensagem _"Saitama deve ser careca"_, que √© capturada e exibida pelo bloco **Catch**.

<p align="right">
    <a href="#sumario">
        <img src="https://raw.githubusercontent.com/JosManoel/Dart-Study/main/images/icons/voltar_ao_topo.png" height="32">
    </a>
</p>

***

<h2 id="Rethrow">Rethrow</h2>

No Dart, al√©m de capturar as exce√ß√µes, tamb√©m √© poss√≠vel relan√ß√°-las para poderem ser tratadas em outros n√≠veis mais complexos. Essa tarefa originalmente poderia ser feita atrav√©s do **Throw**, no entanto, para melhorar a sintaxe e tornar o c√≥digo mais leg√≠vel, o Dart adicionou um recurso denominado **Rethrow**, respons√°vel por relan√ßar uma exce√ß√£o capturada para um n√≠vel mais alto.

O **Rethrow** possui uma sintaxe ainda mais simples, bastando cham√°-lo ao fim do bloco de tratamento.

<h3 align="center">Sintaxe de utiliza√ß√£o do Rethrow</h3>

~~~dart
//Bloco de tratamento de excecao 
//... 
rethrow;
//...
~~~

<h3 align="center">Rethrow - Exemplo pr√°tico</h3>

~~~dart
main() { 
   var saitama_forca = 10; 
   var saitama_cabelo = 0; 
   var saitama_poder;  
   
   try {  
     if(saitama_cabelo > 0){
        throw FormatException("Saitama deve ser careca");  
     }
     
     saitama_poder = saitama_forca ~/ saitama_cabelo;
     print("N√≠vel de poder do Saitama: ${saitama_poder}");
   }  
   on UnsupportedError{ 
      print("Erro capturado pelo bloco On"); 
      print("UnsupportedError: opera√ß√£o inv√°lida"); 
      rethrow;
   }
   catch(e) { 
      print("Erro capturado pelo bloco Catch"); 
      print(e);
   }
   finally {
     print("C√°lculo de poder do Saitama encerrado");
   }
}    
~~~

> Note que agora o console tamb√©m retorna um "Uncaught Error", resultado do tratamento do "UnsupportedError" em um n√≠vel mais alto. 

<p align="center">
    <a href="https://dartpad.dev/?id=731be0b9bac48f1ed677b04929566fca">
        <img src="https://i.imgur.com/7QUft2k.png" height="24">
    </a>
</p>


<p align="right">
    <a href="#sumario">
        <img src="https://raw.githubusercontent.com/JosManoel/Dart-Study/main/images/icons/voltar_ao_topo.png" height="32">
    </a>
</p>

***
<h2 id="#Personalizadas">Exce√ß√µes personalizadas</h2>

O Dart permite ainda a cria√ß√£o de exce√ß√µes personalizadas para suas aplica√ß√µes. Do mesmo modo que as outras exce√ß√µes s√£o subtipos da classe interna "_Exception_", no Dart, as exce√ß√µes personalizadas tamb√©m s√£o extens√µes desta classe. Apesar de trazer novos elementos, sua sintaxe ainda continua bastante simples, possuindo a seguinte estrutura:


<h3 align="center">Exce√ß√µes personalizadas - Sintaxe</h3>

~~~dart
class Nome_da_excecao_personalizada implements Exception {
    //instru√ß√µes para o tratamento de exce√ß√µes
}
~~~

Note que agora utilizamos fortemente o conceito de classes, com termos como "_class_" e "_implements_". Apesar deste tema ainda n√£o ter sido abordado, seu completo entendimento n√£o ser√° necess√°rio neste momento. Por enquanto, iremos utiliz√°-los apenas como "membros da sintaxe". Posteriormente entraremos a fundo e suas defini√ß√µes no t√≥pico sobre classes.

As exce√ß√µes personalizadas possuem certas peculiaridades quanto a sua utiliza√ß√£o quando comparada as demais. Por exemplo, para que uma exce√ß√£o personalizada retorne uma mensagem de erro, ser√° necess√°rio antes criar uma fun√ß√£o que ser√° respons√°vel por efetuar o retorno da mensagem, quando chamada. A cria√ß√£o desta fun√ß√£o pode ser efetuada de diversas formas, mas a sintaxe mais utilizada para execut√°-la √© a [Big Arrow Function](https://github.com/JosManoel/Dart-Study/blob/main/topics/2-1_Criando_funcoes.md#BigArrowF), por ser mais compacta. Para que seja exibida a mensagem de erro, ser√° necess√°rio chamar a classe da exce√ß√£o personalizada com sua fun√ß√£o, conforme a seguinte sintaxe:

<h3 align="center">Exce√ß√µes personalizadas - Mensagem de erro</h3>

~~~dart
class Nome_da_excecao_personalizada implements Exception {
    String mensagem_de_erro()=> "Texto de erro";
}

//...

//Printando a mensagem na tela.
print(Nome_da_excecao_personalizada.mensagem_de_erro());
~~~

Para o uso de exce√ß√µes customizadas tamb√©m √© recomendado que se utilize outras fun√ß√µes para lan√ßar o erro com o uso do **throw**. Deste modo, √© poss√≠vel manter o tratamento de erro separado do lan√ßamento de exce√ß√µes, mantendo o c√≥digo leg√≠vel.

<h3 align="center">Exce√ß√µes personalizadas - Exemplo pr√°tico</h3>

~~~dart
// Exce√ß√£o customizada
class carecaException implements Exception{
  String erroMsg()=> "Saitama deve ser careca";
}

main() { 
   var saitama_forca = 10; 
   var saitama_cabelo = 1; 
   var saitama_poder;  
   
   try {  
     carecaChecker(saitama_cabelo);
     
     saitama_poder = saitama_forca ~/ saitama_cabelo;
     print("N√≠vel de poder do Saitama: ${saitama_poder}");
   }  
   on carecaException{ 
     carecaException e = carecaException();
     print(e.erroMsg());
   }

   finally {
     print("C√°lculo de poder do Saitama encerrado");
   }
}   

// Fun√ß√£o de verifica√ß√£o
void carecaChecker(cabelo){
  if(cabelo > 0){
    throw carecaException();  
  }
}
~~~

<p align="center">
    <a href="https://dartpad.dev/?id=30aa169e8ccfcd22adb8ec865e6805d9">
        <img src="https://i.imgur.com/PBpepuR.png" height="24">
    </a>
</p>

<p align="right">
    <a href="#sumario">
        <img src="https://raw.githubusercontent.com/JosManoel/Dart-Study/main/images/icons/voltar_ao_topo.png" height="32">
    </a>
</p>


***
<h2 id="Dart_core-exception">Dart Core: Exceptions</h2>

O Dart possui uma clara defini√ß√£o quanto a diferen√ßa entre **Exception** e **Error**, utilizando duas bibliotecas distintas para implementar cada um desses elementos. A primeira delas, a **Exception Class** √© definida como uma "interface" para todas as exce√ß√µes da **Dart:core Library**, destinada √† transmiss√£o e capturas de falhas em tempo de execu√ß√£o. 

Por defini√ß√£o, a **Exception Class** deve ser utilizada sempre que queremos tratar um erro esperado, como os exemplos desenvolvidos neste artigo. A **Exception Class** implementa 7 tipos de exce√ß√µes, sendo elas:

* [DeferredLoadException](https://api.dart.dev/stable/2.16.2/dart-async/DeferredLoadException-class.html)
* [FormatException](https://api.dart.dev/stable/2.16.2/dart-core/FormatException-class.html)
* [IOException](https://api.dart.dev/stable/2.16.2/dart-io/IOException-class.html)
* [IsolateSpawnException](https://api.dart.dev/stable/2.16.2/dart-isolate/IsolateSpawnException-class.html)
* [NullRejectionException](https://api.dart.dev/stable/2.16.2/dart-js_util/NullRejectionException-class.html)
* [OSError](https://api.dart.dev/stable/2.16.2/dart-io/OSError-class.html)
* [TimeoutException](https://api.dart.dev/stable/2.16.2/dart-async/TimeoutException-class.html)

A documenta√ß√£o completa da **Exception Class** pode ser encontrada [neste link](https://api.dart.dev/stable/2.16.2/dart-core/Exception-class.html).

<p align="right">
    <a href="#sumario">
        <img src="https://raw.githubusercontent.com/JosManoel/Dart-Study/main/images/icons/voltar_ao_topo.png" height="32">
    </a>
</p>

***

<h2 id="Dart_core-error">Dart Core: Error</h2>

Ao contr√°rio da **Exception**, a **Error Class** trata de erros do software e n√£o devem ser capturados, mas sim endere√ßados ao desenvolvedor, para que possam ser corrigidos fora do tempo de execu√ß√£o. Apesar de tamb√©m ser poss√≠vel captur√°-los com o tratamento de exce√ß√µes, como feito com o _UnsupportedError_ em alguns dos exemplos, a sua utiliza√ß√£o para estes fins √© fortemente desencorajada, sendo mais usual e seguro o encerramento por completo da aplica√ß√£o.

De modo geral, um **Error** pode ser definido como uma falha no programa que o desenvolvedor deveria ter evitado, como chamar uma fun√ß√£o com argumentos inv√°lidos ou um momento que n√£o era permitido. 

A variedade de erros implementados pela **Error Class** √© bem mais amplo que as 7 principais exce√ß√µes da **Exception Class** e podem ser acessados a partir de sua [documenta√ß√£o](https://api.dart.dev/stable/2.16.2/dart-core/Error-class.html).

<p align="right">
    <a href="#sumario">
        <img src="https://raw.githubusercontent.com/JosManoel/Dart-Study/main/images/icons/voltar_ao_topo.png" height="32">
    </a>
</p>




***
<h2 id="#leitura_e_link"> üìö Leitura e links recomendados </h2>

* [üìù Dart - Documenta√ß√£o](https://dart.dev/guides)
* [üéØ Language Tuor: Exceptions](https://dart.dev/guides/language/language-tour#exceptions)
* [üéØ Library Tuor: Exceptions](https://dart.dev/guides/libraries/library-tour#exceptions)
* [üéØ Dart:core library - Exception class](https://api.dart.dev/stable/2.16.2/dart-core/Exception-class.html)
* [üéØ Dart:core library - Error class](https://api.dart.dev/stable/2.16.2/dart-core/Error-class.html)
* [üéØ Dart ‚Äì Types of Exceptions](https://www.geeksforgeeks.org/dart-types-of-exceptions/)
* [üéØ Dart Programming - Exceptions](https://www.tutorialspoint.com/dart_programming/dart_programming_exceptions.htm)
* [üéØ Do use retrow to rethrow a caught exception](https://dart.dev/guides/language/effective-dart/usage#do-use-rethrow-to-rethrow-a-caught-exception)
* [üéØ use_rethrow_when_possible](https://dart-lang.github.io/linter/lints/use_rethrow_when_possible.html)
* [üéØ Dart - Creating Custom Exception Class](https://www.woolha.com/tutorials/dart-creating-custom-exception-class)
* [üéØ avoid_catching_errors](https://dart-lang.github.io/linter/lints/avoid_catching_errors.html)

<p align="right">
    <a href="#sumario" style="font-size:1rem;font-weight: bold;">
        <img src="https://raw.githubusercontent.com/JosManoel/Dart-Study/main/images/icons/voltar_ao_topo.png" height="32">
    </a>
</p>

***
<h2 id="#licenca"> üßæLicen√ßa </h2>

Este projeto est√° sob a licen√ßa [Apache 2.0](https://github.com/JosManoel/Dart-Study/blob/main/LICENSE).

<p align="right">
    <a href="#sumario" style="font-size:1rem;font-weight: bold;">
        <img src="https://raw.githubusercontent.com/JosManoel/Dart-Study/main/images/icons/voltar_ao_topo.png" height="32">
    </a>
</p>
